package com.tulip.host.enums;

public enum ExpenseTypeEnum {
    OFFICE_MAINTENANCE,
    STUDENT_DISCOUNT,
    BILLS,
    STUDENT_DISCOUNT,
    ANNUAL_FUNCTION,
    ANNUAL_SPORTS,
    SCHOOL_CELEBRATION,
    EXAM_BILLS,
    SCHOOL_INFRASTRUCTURE,
    PRINCIPAL_OFFICE,
    SCHOOL_UPGRADE,
    OTHERS,
}
